<?php

// tokens.css is never shipped; a request that finds it missing compiles it from
// config/tokens.php. The original file is restored afterwards.

test('missing tokens.css is regenerated by the next request', function () {
    $root = dirname(__DIR__);
    $file = $root . '/public/cache/tokens.css';
    $original = is_file($file) ? file_get_contents($file) : null;

    try {
        if ($original !== null) {
            unlink($file);
        }
        assertTrue(!is_file($file), 'tokens.css still exists before dispatch');

        $response = dispatch('/hello');
        assertTrue(is_file($file), 'tokens.css was not regenerated by the request');
        assertContains('href="/cache/tokens.css"', $response->body, 'page');

        $css = (string) file_get_contents($file);
        foreach (require $root . '/config/tokens.php' as $group => $values) {
            foreach ($values as $name => $value) {
                assertContains("--{$group}-{$name}: {$value};", $css, 'tokens.css');
            }
        }
    } finally {
        if ($original === null) {
            is_file($file) && unlink($file);
        } else {
            file_put_contents($file, $original);
        }
    }
});
